# Generated by Django 5.1.15 on 2026-08-23 22:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(max_length=20)),
                ('wheelchair_capable', models.BooleanField(default=False)),
                ('stretcher_capable', models.BooleanField(default=False)),
                ('passenger_capacity', models.PositiveIntegerField()),
                ('registration_expiration_date', models.DateField()),
                ('inspection_expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'In maintenance'), ('out_of_service', 'Out of service'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['make', 'model'],
            },
        ),
    ]
