# Generated by Django 5.1.15 on 2026-08-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_seed_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ein',
            field=models.CharField(blank=True, help_text='Internal use only -- not published on the public site.', max_length=20, verbose_name='EIN'),
        ),
    ]
