# Generated by Django 5.1.15 on 2026-08-30 00:58

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('payer_type', models.CharField(choices=[('medicaid_mco', 'Medicaid MCO'), ('broker', 'Broker'), ('private_pay', 'Private Pay'), ('facility_contract', 'Facility Contract'), ('other', 'Other')], max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9()+\\-.\\s]{7,20}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
