# Generated by Django 5.1.15 on 2026-08-23 21:54

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=200)),
                ('preferred_name', models.CharField(blank=True, help_text='If different from legal name (e.g. a nickname).', max_length=200)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9()+\\-.\\s]{7,20}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9()+\\-.\\s]{7,20}$')])),
                ('preferred_service_type', models.CharField(blank=True, choices=[('ambulatory', 'Ambulatory'), ('wheelchair', 'Wheelchair'), ('stretcher', 'Stretcher')], max_length=20)),
                ('mobility_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['legal_name'],
            },
        ),
    ]
