# Generated by Django 5.1.15 on 2026-08-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='preferred_service_type',
            field=models.CharField(blank=True, choices=[('ambulatory', 'Ambulatory'), ('wheelchair', 'Wheelchair'), ('stretcher', 'Stretcher'), ('equipment_delivery', 'Medical Supply & Equipment Delivery')], max_length=20),
        ),
    ]
