# Generated by Django 5.1.15 on 2026-08-30 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_alter_passenger_preferred_service_type'),
        ('payers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to='payers.payer'),
        ),
    ]
