# Generated by Django 5.1.15 on 2026-08-23 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('transportation', '0002_triprequest_passenger'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_pickup_datetime', models.DateTimeField(help_text="Confirmed pickup time, stored in UTC -- may differ from the trip request's originally requested time.")),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver')),
                ('trip_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trip', to='transportation.triprequest')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-scheduled_pickup_datetime'],
            },
        ),
    ]
