# Generated by Django 5.1.15 on 2026-08-22 23:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9()+\\-.\\s]{7,20}$')])),
                ('email', models.EmailField(max_length=254)),
                ('pickup_address', models.TextField()),
                ('dropoff_address', models.TextField()),
                ('requested_datetime', models.DateTimeField(help_text='Requested pickup date/time, stored in UTC.')),
                ('service_type', models.CharField(choices=[('ambulatory', 'Ambulatory'), ('wheelchair', 'Wheelchair'), ('stretcher', 'Stretcher')], max_length=20)),
                ('mobility_notes', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('source', models.CharField(default='website', help_text='Where this request originated (website, phone, etc.).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
