# Generated by Django 5.1.15 on 2026-08-23 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_requests', to='passengers.passenger'),
        ),
    ]
