# Generated by Django 5.1.15 on 2026-08-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_triprequest_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='service_type',
            field=models.CharField(choices=[('ambulatory', 'Ambulatory'), ('wheelchair', 'Wheelchair'), ('stretcher', 'Stretcher'), ('equipment_delivery', 'Medical Supply & Equipment Delivery')], max_length=20),
        ),
    ]
