# Generated by Django 5.1.15 on 2026-08-30 17:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('payers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(blank=True, help_text="The payer's own reference number, once known.", max_length=100)),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('paid', 'Paid')], default='submitted', max_length=20)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='billing.invoice')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='payers.payer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
